# Generated by Django 5.2 on 2025-05-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='currencies',
        ),
        migrations.AddField(
            model_name='country',
            name='timezone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
