# Generated by Django 5.2 on 2025-05-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_remove_country_currencies_country_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.FloatField(null=True),
        ),
    ]
