# Generated by Django 5.2 on 2025-05-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_country_population_alter_country_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='timezone',
        ),
    ]
